### ISSUE TITLE
Improve example player move so when pressing against walls the camera doesn't shake

### ISSUE THREAD

**Issue by subsoap** [astrochili/defold-kinematic-walker#8] opened 2022-09-30 05:09 UTC
This may give bad impression to people considering this tool if they don't know how to fix it themselves

When pressing against walls and not moving camera shakes, this shouldn't happen to look better

**Comment by astrochili** [comment] 2022-12-18 20:27
@subsoap Thank you very much for your participation!

Yes, this is indeed a problem in the kinematic walker. The player's body is being thrown back. The problem here is not even that the player is being thrown (it should be), but that the frame is rendered when the player's position is invalid BEFORE being thrown back.

That is, ideally, the attempt to enter the wall and throwing away from it - this process should take place behind the scenes of one frame without rendering the position "inside the wall". 

I hope that what I can reproduce on my M1 (jitter outside the building) is the same problem and then I can deal with it.

**Comment by astrochili** [comment] 2022-12-19 17:21
At the moment I tested on:

- Macbook M1 2021 - fine.
- Macbook Air 2012 - fine.
- Old laptop 2010 with Windows - very bad, the character starts rocking back and forth and falls off the level during few seconds.

Current Defold project settings:
- Vsync is on;
- Update frequency is 0;
- Fixed update frequency is 60;
- Use Fixed Timestamp is off;
- Max fixed timestamps is 2;

The current code doesn't contains the `fixed_update()` function, everything works with the `update()` and `on_message()` functions at the moment.

**Comment by subsoap** [comment] 2022-12-19 18:42
If you implement fixed_update() I will test and see results!
I can try too but likewise have time constraints right now...

**Comment by subsoap** [comment] 2022-12-29 20:56
I tested downloading this project, editing walker.script and changing update to fixed_update and with fixed_update I do see significantly less bouncing when pushing against an object.

update:


https://user-images.githubusercontent.com/409170/210010199-3a60b703-6305-46cb-881b-3b7c9e47842e.mp4

fixed_update:


https://user-images.githubusercontent.com/409170/210010207-75b7d42f-4424-43a8-9e22-5a14873487fe.mp4

maybe the bouncing effect still present in fixed_update could be eliminated by smoothing movement at small distance chances?

in this demo, at this position could you record what you see/is there still a little bit of bounce?

**Comment by subsoap** [comment] 2022-12-29 21:00
Anyway, changing from update to fixed_update seems right thing to do here to improve it!

The video you posted above is similar in shaking when pressing against a surface as I see now.

**Comment by subsoap** [comment] 2022-12-29 21:13
I tested moving just the first ground test into fixed_update and it does improve jumping visually.  So all physics checks have to be moved into fixed_update and then all movement sim remains in update?

The first update always happens before the first fixed_update for me.

**Comment by astrochili** [comment] 2022-12-30 14:30
I caught shaking with `update()` on my machine but only in the screen recording mode 😄

### `update()` without screen recording (the most expected result)

https://user-images.githubusercontent.com/4752473/210075607-49bba05a-edde-4212-9f38-4350e2545359.mp4

### `update()` with screen recording (bounces and an unstable pink line are here)

https://user-images.githubusercontent.com/4752473/210076242-86903c09-f49a-401b-ac3b-010437ebb1a8.mp4

### `fixed_update()` with screen recording (luxury bounces from iOS scrollviews)

https://user-images.githubusercontent.com/4752473/210076361-588d82e9-4543-4387-9c63-7ae90765c18f.mp4

I can also confirm that from time to time with `fixed_update()` I get the same interruptions when moving as you get when jumping. In your video you can see that it happens not only while jumping, but also while walking, it is just less noticeable because of the camera angle.

### What do we have at the moment?

- Yes, `fixed_update()` improves the situation, but leads to too different results, according to our videos. With me it's a "smooth in and out" the obstacle, and with you it's still bouncing.
- Perhaps `fixed_update()` only reduces the performance load, allowing the bug to avoid attention.
- But you can definitely see that `fixed_update()` leads to unacceptable glitches in the movement (both you and me have them).
- Probably, all this can be solved by refactoring for new realities.

In theory (in desirable theory), any bounces can be solved by refusing to move beforehand. In Unity, as far as I know, there's an option to use ghost-body to pre-check all collisions in a frame without moving objects.

Here we first move the character by input values `update()`, get a collision message, move the body, get the message again, move it, get the message again, move it again... and the hope is that it all happens before drawing. After that we move the character by input values in `update()` again and the whole cycle starts the next round.

```
- on_input() -> update() -> on_message -> handle_contact_point_response -> on_message -> handle_contact_point_response -> ...
- on_input() -> update() -> ...
```

I'd like to look into it, but I'm still busy with offline questions. The first thing I would do is comment out a lot of forks in `handle_contact_point_response` to see exactly where the problem occurs. And the second would be to figure out how `fixed_update` can be useful in this paradigm and what should logically be there.

**Comment by astrochili** [comment] 2023-05-17 15:04
Well, I also moved all the code from `update()` to `fixed_update()` and set to the project settings:

- `use_fixed_timestep = 1`
- `max_fixed_timesteps = 1`

If ignore the bounces not related to physics (while jumping, walkingб etc.), it seems to work.

Regarding the new visual artifacts. I noticed that it happens exactly when update() is called more often than fixed_update(). This is the expected behavior of these functions and I think the visual artifacts happen because the camera position update cycle is performs in the `update()` (which makes sense) and happens more often than the player body position changes (since it's changing in `fixed_update()`).

Ideally, player rendering should happen also in `update()`, but in order to do so I need to separate the player model and his physical body from each other by setting their positions in different runloop functions. Then, theoretically, everything should be fine, they are still working on it.

**Comment by astrochili** [comment] 2023-05-17 15:27
To be precise, artifacts occur when calls look like this. I don't know if this is normal.

![](https://github.com/astrochili/defold-kinematic-walker/assets/4752473/3e79f45e-8c71-4e61-8698-f55e820d3829)

**Comment by astrochili** [comment] 2023-05-17 16:14
Well, after a little investigation, I realized that this is normal. It is, in fact, a drop in FPS. If `update()` suddenly gains more than 1/60th of a second, it is followed by more `fixed_update()` at a time. Accordingly, at one moment the code is executed twice, which does something that should not do twice :D

**Comment by astrochili** [comment] 2023-05-17 16:33
Recorded two videos where you can watch frame by frame.
https://github.com/astrochili/defold-kinematic-walker/assets/4752473/6442357e-fda1-414e-b67e-3f0d1a5ff7f8
https://github.com/astrochili/defold-kinematic-walker/assets/4752473/5b997979-fd3c-4578-8753-70d597aecaf3

**Comment by astrochili** [comment] 2023-05-17 19:02
Good to know that this is common problem of using fixedUpdate — https://kinematicsoup.com/news/2016/8/9/rrypp5tkubynjwxhxjzd42s3o034o8

**Comment by astrochili** [comment] 2023-05-17 21:55
Started experimenting with forced `fixed_update_frequency = 10`, I'm sure if I get a great result here, I'll get a great result on 60 :) So far, not much progress.

**Comment by astrochili** [comment] 2023-05-19 06:59
I created a branch [fixed-update-migration](https://github.com/astrochili/defold-kinematic-walker/tree/fixed-update-migration), which I think solved the problem. I separated the physical body and move it first, to get collision messages, and only then interpolate the visual body.

The first thing that is strange is that with `display.update_frequency = 10` and `engine.fixed_update_frequency = 60` makes the game 6 times slower. It is not clear whether `engine.fixed_update_frequency` is an emulation of a lower FPS in this case or everything is ok and we just never need to make `display.update_frequency` less than `engine.fixed_update_frequency`.

The second thing is that the tilt detectors, both bottom and top, broke, but that seems to be another consequence of the loop shift, I'm sure it can be handled.

**Comment by astrochili** [comment] 2023-05-19 08:07
Okay, also fixed slope detection. So now everything works like it worked before `fixed_update()` I think. Old bugs are old bugs, but no jitter in the walls.

@subsoap @ReanimatorXP Please, when you have time, check the branch https://github.com/astrochili/defold-kinematic-walker/tree/fixed-update-migration. Yes, there are some old bugs in there (sometimes you can get stuck in the top slope with character head or you can get jitter in front of pillar), but they were there before. In the branch, I seem to have solved the jitter problem according this issue.

**Comment by subsoap** [comment] 2023-05-26 20:13
Confirming no more jitter!

**Comment by ReanimatorXP** [comment] 2023-06-08 05:51
Cool, you did a great job! I also comfirm - no jitter anymore.
There's a thing that I'm not sure what it has to do with.

1. The character gets stuck when exiting the tunnel (pipe). Here is a video:
https://github.com/astrochili/defold-kinematic-walker/assets/24944063/2a208224-2623-4ff2-86b6-9a14b305f577
From the video you can see how it happens. Make a jump while crouching inside the pipe (or fall down from the very top) and here is a chance to get stuck at the exit. I couldn't reproduce it in the old version (which I remade to use 'fixed_update') nor in the HTML demo.

Other than that, I couldn't find any regressions. So it looks very viable.

**Comment by astrochili** [comment] 2023-06-08 08:57
@ReanimatorXP Confirmed, this is a new bug. Needs to be fixed.)

**Comment by astrochili** [comment] 2023-06-10 15:49
The new bug about tube turned out to be an old one, I just changed the length of the sensor from 0.05 to 0.1 in migration branch for some reason. Created https://github.com/astrochili/defold-kinematic-walker/issues/11.

Merged the result of migration to the master, thanks you guys!

**Closed by astrochili** 2023-06-10 15:49 UTC
